/* CLASS REPRESENTING THE 'CHATPHOTO' OBJECT FROM TELEGRAM OFFICIAL DOCS:
 *  https://core.telegram.org/bots/api#chatphoto
 *
 *  THE NAMING CONVENTION FOR ATTRIBUTES IS KEPT AS attribute_name (AS USED IN OFFICIAL DOCS)
 *  FOR CORRECT SERIALIZATION LATER ON WITH GSON EXTERNAL LIBRARY.
 *  THE CLASS METHODS FOLLOW THE JAVA NAMING CONVENTIONS.
 *
 *  STATUS: INCOMPLETE
 *  ATTRIBUTES NEED TO BE ADDED
 */

package model.telegram.available_types;

public class TelegramChatPhoto {
}
